export const HERO_WIDTH = 400;
export const HERO_HEIGHT = 240;

export const CARD_BODY_HEIGHT = 120;
export const CARD_COLLAPSED_HEIGHT = HERO_HEIGHT + CARD_BODY_HEIGHT;
export const CARD_EXPANDED_EXTRA = 140;
export const CARD_EXPANDED_HEIGHT = CARD_COLLAPSED_HEIGHT + CARD_EXPANDED_EXTRA;

export const ITINERARY_CHIP_WIDTH = 160;
export const ITINERARY_CHIP_HEIGHT = 100;
